{
  "mcpServers": {
    "neo4j-memory": {
	"type": "stdio",
	"command": "python",
	"args": ["/path/to/project/neo4j-memory-server/src/neo4j_memory_server/server.py"],
      "env": {
        "NEO4J_URI": "bolt://localhost:7687",
        "NEO4J_USERNAME": "neo4j",
        "NEO4J_PASSWORD": "your-password"
      }
    }
  }
}